version: '2'
services:
  web-app-db:
    container_name: "web-db"
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webapp-db
    ports:
      - 3307:3306
    networks:
      - infoshare_network
    volumes:
      - /home/milo/mfinance/web-app/db-files:/var/lib/mysql

  web-app:
    container_name: "web-app"
    build: ./jboss-web-app
    ports:
      - 8080:8080
      - 9990:9990
      - 5005:5005
    networks:
      - infoshare_network
    volumes:
      - ../mfinance-webapp/target:/opt/jboss/wildfly/standalone/deployments

networks:
  infoshare_network:
    driver: bridge